name: sonosvolume
version: git
summary: Sonos Volume web-app
description: >
  Tiny web-app used to see and change the volume of Sonos speakers.
grade: devel
confinement: strict
base: core18

apps:
  sonosvolume:
    command: bin/sonosvolume
    plugs:
      - network
      - network-bind
    daemon: simple

parts:
  sonosvolume:
    plugin: python
    source: .
